apiVersion: apps/v1
kind: Deployment

metadata:
  name:  todo-deployment
  namespace: default
  labels:
    app:  todo-deployment-label

spec:
  selector:
    matchLabels:
      app: todo-deployment-label

  replicas: 1

  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: todo-deployment-label

  spec:
      containers:
      - name:  todo-container
        image:  todo-image:latest 
        imagePullPolicy: IfNotPresent #Always
        command: ['rails', 's']
        # resources:
        #   requests:
        #     cpu: "1"
        #     memory: 200Mi
        #   limits:
        #     cpu: "20"
        #     memory: 1Gi

      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: todo-db-secret
              key: todo-db-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-db-secret
              key: todo-db-password
        - name: POSTGRES_HOST
          value: todo-db-service
        - name: RUBY_ALLOWED_HOSTS
          value: '*'

      ports:
        - containerPort:  8080
          name:  todo-container

      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: default
spec:
  selector:
    app: todo-label
  type: LoadBalancer
  ports:
  - protocol: TCP
    # this service will expose this port
    port: 8080
    # Port we're targeting on the pod container
    targetPort: 8080